import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../data/models/models.dart';
import '../../data/repositories/seller_repository.dart';
import 'seller_event.dart';
import 'seller_state.dart';

class SellerBloc extends Bloc<SellerEvent, SellerState> {
  final SellerRepository _sellerRepository;

  SellerBloc({required SellerRepository sellerRepository})
      : _sellerRepository = sellerRepository,
        super(SellerInitial()) {
    on<LoadStore>(_onLoadStore);
    on<SaveStore>(_onSaveStore);
    on<LoadSellerProducts>(_onLoadSellerProducts);
    on<CreateProductEvent>(_onCreateProduct);
    on<UpdateProductEvent>(_onUpdateProduct);
    on<DeleteProductEvent>(_onDeleteProduct);
  }

  Future<void> _onLoadStore(LoadStore event, Emitter<SellerState> emit) async {
    emit(StoreLoading());
    try {
      final store = await _sellerRepository.getStoreBySellerId(event.sellerId);
      emit(StoreLoaded(store));
    } catch (e) {
      emit(StoreError('Gagal memuat data toko: ${e.toString()}'));
    }
  }

  Future<void> _onSaveStore(SaveStore event, Emitter<SellerState> emit) async {
    emit(StoreLoading());
    try {
      if (event.name.trim().isEmpty || event.description.trim().isEmpty) {
        return emit(const StoreError('Nama dan deskripsi toko wajib diisi!'));
      }

      Store store;
      if (event.storeId == null) {
        // Create new
        final newStore = Store(
          id: '', // database will generate uuid
          sellerId: event.sellerId,
          name: event.name.trim(),
          description: event.description.trim(),
          location: event.location.trim(),
          logoUrl: event.logoUrl,
          rating: 5.0,
        );
        store = await _sellerRepository.createStore(newStore);
      } else {
        // Update existing
        final existingStore = Store(
          id: event.storeId!,
          sellerId: event.sellerId,
          name: event.name.trim(),
          description: event.description.trim(),
          location: event.location.trim(),
          logoUrl: event.logoUrl,
          rating: 5.0,
        );
        store = await _sellerRepository.updateStore(existingStore);
      }

      emit(StoreSavedState(store));
      emit(StoreLoaded(store));
    } catch (e) {
      // Capture custom exception messages (e.g. database uniqueness error)
      String errorMsg = e.toString();
      if (errorMsg.contains('Exception:')) {
        errorMsg = errorMsg.replaceAll('Exception:', '').trim();
      }
      emit(StoreError(errorMsg));
    }
  }

  Future<void> _onLoadSellerProducts(LoadSellerProducts event, Emitter<SellerState> emit) async {
    emit(ProductsLoading());
    try {
      final products = await _sellerRepository.getProductsByStoreId(event.storeId);
      emit(ProductsLoaded(products));
    } catch (e) {
      emit(ProductsError('Gagal memuat produk: ${e.toString()}'));
    }
  }

  Future<void> _onCreateProduct(CreateProductEvent event, Emitter<SellerState> emit) async {
    emit(ProductsLoading());
    try {
      if (event.name.trim().isEmpty || event.description.trim().isEmpty) {
        return emit(const ProductsError('Semua kolom wajib diisi!'));
      }
      if (event.price <= 0) {
        return emit(const ProductsError('Harga harus lebih besar dari 0!'));
      }
      if (event.stock < 0) {
        return emit(const ProductsError('Stok tidak boleh bernilai negatif!'));
      }

      final newProduct = Product(
        id: '', // generated by database
        storeId: event.storeId,
        name: event.name.trim(),
        price: event.price,
        stock: event.stock,
        description: event.description.trim(),
        imageUrl: event.imageUrl,
        category: event.category,
        rating: 5.0,
        reviewCount: 0,
      );

      await _sellerRepository.createProduct(newProduct);
      emit(const ProductCrudSuccess('Produk berhasil ditambahkan!'));
      
      // Reload products list
      final products = await _sellerRepository.getProductsByStoreId(event.storeId);
      emit(ProductsLoaded(products));
    } catch (e) {
      String errorMsg = e.toString();
      if (errorMsg.contains('Exception:')) {
        errorMsg = errorMsg.replaceAll('Exception:', '').trim();
      }
      emit(ProductsError(errorMsg));
    }
  }

  Future<void> _onUpdateProduct(UpdateProductEvent event, Emitter<SellerState> emit) async {
    emit(ProductsLoading());
    try {
      if (event.name.trim().isEmpty || event.description.trim().isEmpty) {
        return emit(const ProductsError('Semua kolom wajib diisi!'));
      }
      if (event.price <= 0) {
        return emit(const ProductsError('Harga harus lebih besar dari 0!'));
      }
      if (event.stock < 0) {
        return emit(const ProductsError('Stok tidak boleh bernilai negatif!'));
      }

      final product = Product(
        id: event.id,
        storeId: event.storeId,
        name: event.name.trim(),
        price: event.price,
        stock: event.stock,
        description: event.description.trim(),
        imageUrl: event.imageUrl,
        category: event.category,
        rating: 5.0,
        reviewCount: 0,
      );

      await _sellerRepository.updateProduct(product);
      emit(const ProductCrudSuccess('Produk berhasil diperbarui!'));
      
      // Reload products list
      final products = await _sellerRepository.getProductsByStoreId(event.storeId);
      emit(ProductsLoaded(products));
    } catch (e) {
      String errorMsg = e.toString();
      if (errorMsg.contains('Exception:')) {
        errorMsg = errorMsg.replaceAll('Exception:', '').trim();
      }
      emit(ProductsError(errorMsg));
    }
  }

  Future<void> _onDeleteProduct(DeleteProductEvent event, Emitter<SellerState> emit) async {
    emit(ProductsLoading());
    try {
      await _sellerRepository.deleteProduct(event.productId);
      emit(const ProductCrudSuccess('Produk berhasil dihapus!'));
      
      // Reload products list
      final products = await _sellerRepository.getProductsByStoreId(event.storeId);
      emit(ProductsLoaded(products));
    } catch (e) {
      emit(ProductsError('Gagal menghapus produk: ${e.toString()}'));
    }
  }
}
